version: '3.8'

services:
  nginx:
    image: nginx
    hostname: test_nginx
    container_name: test_nginx
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ../public:/app/public:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - 8088:80

  app:
    hostname: test_app
    container_name: test_app
    build:
      context: app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ../:/var/www/html/:cached
      - ../migrations:/app/migrations:cached

  db:
    hostname: test_db
    container_name: test_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5431:5432

volumes:
  db_data:
